services:
#   # ------------ TU APLICACIÃ“N (PyGoat) ------------
#   web:
#     build: .
#     command: gunicorn --bind 0.0.0.0:8000 --workers 6 pygoat.wsgi
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     depends_on:
#       - migration

#   migration:
#     image: pygoat/pygoat:latest
#     command: python manage.py migrate --noinput
#     volumes:
#       - .:/app

  # ------------ DEPENDENCY-TRACK API SERVER ------------
  dtrack-apiserver:
    image: dependencytrack/apiserver
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8080"
    volumes:
      - dependency-track:/data
    restart: unless-stopped

  # ------------ DEPENDENCY-TRACK FRONTEND ------------
  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://localhost:8081
    ports:
      - "8082:8080"
    restart: unless-stopped

volumes:
  dependency-track:
